#!/usr/bin/env bash

set -eu

repo_uri="https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
remote_name="origin"
main_branch="master"
target_branch="master"

cd "$GITHUB_WORKSPACE"

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"

git checkout "$target_branch"
git rebase "${remote_name}/${main_branch}"

npm install drive-db
npm install node-fetch
npm install moment
npm install moment-timezone

cp ./faq.json ./faq_prev.json
cp ./tnc.json ./tnc_prev.json
cp ./links.json ./links_prev.json
cp ./doctors.json ./doctors_prev.json

node sheet-to-json_generic.js

rm ./faq_prev.json
rm ./tnc_prev.json
rm ./links_prev.json
rm ./doctors_prev.json

set +e  # Grep succeeds with nonzero exit codes to show results.
git status | grep 'new file\|modified'
if [ $? -eq 0 ]
then
    set -e
    git commit -am "data updated on - $(date)"
    git remote set-url "$remote_name" "$repo_uri" # includes access token
    git push --force-with-lease "$remote_name" "$target_branch"
else
    set -e
    echo "No changes since last run"
fi

echo "finish"
